
import './../globals.css'



export const metadata = {
  title: 'GuinchApp',
  description: 'Generated by create next app',  
  icons: {
    icon: '../../logo2.svg', // /public path
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <link rel="icon" type="image/svg+xml" href="./public/logo2.svg" />
      <body>{children}</body>
    </html>
  )
}
