import './../globals.css'


export const metadata = {
    title: 'Deshboard',
    description: 'Generated by Next.js',
    icons: {
      icon: '../../logo2.svg', // /public path
    },
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',}
  }
  
  export default function RootLayout({ children }) {
   return (
      <html lang="pt-br">
        <body>{children}</body>
      </html>
    )
  }
  